# Generated by Django 5.0 on 2023-12-14 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packfile",
            name="pack",
        ),
    ]
