# Generated by Django 5.0 on 2023-12-14 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_packfile_pack"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packfile",
            old_name="tier",
            new_name="pack",
        ),
    ]
