# Generated by Django 5.0 on 2023-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_rename_tier_packfile_pack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packfile",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
