# Generated by Django 5.0 on 2023-12-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_packfile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packfile",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
